[package]
name = "vmkit-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.93"
quote = "1.0.38"
syn = { version = "2.0.98", features = ["full"] }
synstructure = { version = "0.13.1" }

[lib]
proc-macro = true 